ai_query_tasks = [
"Analyzing financial market conditions and executing market orders for a large company (e.g. buy/sell stocks)",
  "Moving & packing merchandise in a warehouse for shipping to customers",
  "Analyzing and controlling the flow of traffic in a city",
  "Writing reports and publishing Olympic (or other sports) results, standings, and stats (sports news coverage)",
  "Assembling automobiles in a factory",
  "Translating an article you'd like to read from a foreign language to English",
  "Cleaning your house",
  "Scheduling an important business meeting with several co-workers",
  "Writing reports and publishing updates on House/Senate/gubernatorial races during election day (election news coverage)",
  "Finding products you might be interested in while you're shopping",
  "Driving a truck delivering goods/cargo between cities",
  "Monitoring your health and alerting when you should go to the doctor",
  "Diagnosing whether a person has cancer",
  "Providing and coordinating patient care in a health facility, similar to a small part of what a Registered Nurse might do.",
  "Cooking dinner",
  "Responding to emails at work",
  "Picking songs to listen to",
  "Monitoring farm animals' (e.g., cows) behavior, predicting health issues, and alerting the farmer.",
  "Managing your personal finances/investments (similar to what a financial advisor might do)",
  "Filling out and submitting your federal tax return paperwork",
  "Assisting your elderly parent",
  "Picking a movie to watch",
  "Finding and rescuing survivors after earthquakes",
  "Picking jobs to apply to",
  "Monitoring a person's driving and intervening when they're distracted/in danger of making a mistake (e.g., emergency braking)",
  "Identifying people who attended a political rally",
  "Interviewing job applicants and rating candidates",
  "Predicting the sale value of a real estate property",
  "Helping to locate a missing child by searching public spaces",
  "Buying groceries",
  "Guiding and explaining exhibits in a museum (similar to what a museum tour guide might do)",
  "Editing an internet forum comment before you post it (e.g., for maximum popularity)",
  "Analyzing and sorting legal documents for important information, e.g., to find legal precedents for arguing a case in court (similar to some of what a paralegal might do)",
  "Analyzing and critiquing aesthetic qualities of photographs or other forms of art",
  "Finding people who might like to meet for a date",
  "Inferring damage for insurance purposes after a car accident",
  "Identifying and flagging online hate speech",
  "Explaining the diagnosis and treatment options of depression to a patient ",
  "Explaining the diagnosis and treatment options for the flu to a patient ",
  "In court, determining a defendant's risk (e.g., in committing another crime or missing the court date), to help judges make decisions about bail, sentencing, or parole",
  "Diagnosing whether a person has the flu",
  "Assisting an elderly person with showering or bathing",
  "Picking a movie to watch with a group of friends",
  "Picking a topic to write a short story about",
  "Picking which advertisements to show to people on social media websites",
  "Picking which news stories to show to people on social media websites",
  "Planning menus and developing recipes at a restaurant",
  "Predicting the sexual orientation of a person",
  "Driving to work",
  "Walking your dog",
  "Reviewing a book or a movie",
  "Voting in federal elections",
  "Playing a competitive game (e.g., poker, Starcraft, Dota2)",
  "Tracking important moments and information and creating memory aids for elderly people",
  "Teaching your child elementary school math (e.g., multiplication, fractions)",
  "Taking photos of a planned event, such as a wedding or graduation, similar to what a professional photographer might do.",
  "Advising people on nutrition/their diet to help improve their health, similar to what a nutritionist might do",
  "Identifying and flagging fake/deceptive news articles",
  "Arguing your case when you're a defendant in a criminal court",
  "Asking a person out on a date",
  "Conducting a risk prognosis assessment for deciding which patients to transfer to the ICU given limited resources (intensive care)",
  "Coordinating and oversee construction of a building, e.g., consulting with engineers, surveyors, specialists, and construction workers -- similar to some of what an architect might do.",
  "Detecting and removing fake/deceptive online reviews (e.g., for hotels or products)",
  "Devising treatment plans for patients with cancer",
  "Helping elderly individuals to increase their mobility by guiding them through crowded public spaces (e.g., walking to the grocery store)",
  "Devising treatment plans for patients sick with the flu",
  "Cleaning up toxic waste, e.g., after a chemical spill",
  "Establishing compensation/wage/salary level for an employee",
  "Telling a joke",
  "Identifying the social relationship between two people (e.g., are they friends, a couple, strangers, siblings)",
  "Thinking of conversation topics while hanging out with friends",
  "Breaking up with your romantic partner",
  "Choosing and ordering food to eat for dinner",
  "Deciding on an outfit for you to wear",
  "Deciding which applicants receive a loan from a bank (loan assessment)",
  "Helping stroke patients with physical rehabilitation, by guiding or assisting with exercise motions when needed (similar to what a physical therapist might do as part of their job)",
  "Describing images or scenes for visually impaired people",
  "Designing new clothing to manufacture and sell (similar to what a fashion designer might do)",
  "Writing a birthday card to your mother",
  "Writing a blog post",
  "Writing a novel or a short story (creative writing)",
  "Explaining the diagnosis and treatment options of cancer to a patient ",
  "Babysitting your child",
  "Teaching a religion's doctrine and practices to followers, similar to some of the responsibilities of clergy/religious leaders",
  "Setting tariffs on goods imported from China",
  "Reading bedtime stories to your child",
  "Serving food to customers at a restaurant",
  "Devising treatment plans for patients with depression",
  "Cutting, drying, and styling hair, similar to what a barber or hairstylist might do",
  "Deciding military actions such as whether to launch airstrikes",
  "Deciding which applicants to hire as new employees for an open position at work",
  "Diagnosing whether a person has depression",
  "Detecting/recognizing abnormal or suspicious activities of people in crowds in public places for the purposes of security and safety (similar to part of what a police officer might do)",
  "Drawing or painting something (making art)",
  "Playing a board game (e.g., Monopoly, Scrabble)",
  "Choreographing dance moves for a person to perform",
  "Responding to 911-police incident reports, similar to what a patrol officer might do",
  "Serving on jury duty: deciding if a defendant is innocent or guilty",
  "Brushing your teeth",
  "Picking out and buying a birthday present for an acquaintance",
];

function get_random_task() {
  var i = Math.floor(Math.random()*ai_query_tasks.length);
  return ai_query_tasks[i];
}

function save_task_selection(task) {
  sessionStorage.setItem('task', task);
}

function load_task_selection() {
  var task = sessionStorage.getItem('task');
  if(task === "") {
    task = get_random_task();
  }
  return task;
}

